import time

from selenium.webdriver.common import action_chains

from pages.base_page import BasePage
from locators.konstructor_locator import CreateFolder as create
from locators.konstructor_locator import DeleteFolder as delete
from locators.konstructor_locator import CreateTable as table
from selenium.webdriver import Keys
from selenium.webdriver import ActionChains

class Test_Konstructor(BasePage):
    def create_folder(self):  #Создание папки
        self.autorization()
        self.element_is_present(create.ARROW_DOWN).click()
        self.element_is_visible(create.ADD_FOLDER).click()
        self.element_is_visible(create.EDIT).click()
        Title = self.element_is_present(create.INPUT_TEXT)
        Title.click()
        Title.clear()
        Title.send_keys('30.03.2022')
        self.element_is_present(create.CHECK_MARK).click()
    def delete_folder(self):#Удаление папки
        self.autorization()
        self.element_is_visible(delete.ARROW_DOWN).click()
        self.element_is_visible(delete.ADD_FOLDER).click()
        Move=self.element_is_present(delete.MOVING)
        Place=self.element_is_present(delete.PLACE)
        action_chains=ActionChains(self.driver)
        action_chains.drag_and_drop(Move,Place).perform()
        Move2=self.element_is_present(delete.MOVING2)
        Del= self.element_is_present(delete.DELETE_PLACE)
        action_chains.drag_and_drop(Move2,Del).perform()
        self.driver.switch_to.alert.accept()
    def create_table_directory(self): #Создание таблицы: справочника
        self.autorization()
        self.element_is_present(table.ADD_TABLE).click()
        Table_name = self.element_is_visible(table.TABLE_NAME)
        Table_name.click()
        Table_name.send_keys("Справочник 1 31.03.2023")
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.SECOND_ROW).click()
        names=self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('Строка')
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.THiRD_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('Многострочная строка')
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_MANY_STRING).click()
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.FOUR_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('Целое число')
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_INTENGER).click()
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.FIFTH_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys("Число с плавающей точкой")
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_FLOAT).click()
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.SIXTH_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys("Дата")
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DATA).click()
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.SEVENTH_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys("Дата и время")
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DATA_TIME).click()
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.EIGHTH_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys("Логическое значение")
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_BOOLEAN_VALUE).click()
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.NINETH_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys("Файл")
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_FILE).click()
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.TENTH_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys("HTML")
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_HTML).click()
        self.element_is_visible(table.SAVE).click()
    def Add_help(self): #Создание подсказок
        self.autorization()
        self.element_is_visible(table.EDIT_ADDITIONAL).click()
        self.element_is_visible(table.SECOND_ROW).click()
        self.element_is_visible(table.ADD_ADDITINAL_SETTING).click()
        header=self.element_is_visible(table.ADDITINAL_HEADER)
        header.click()
        header.send_keys("Подсказка в заголовке")
        self.element_is_visible(table.THiRD_ROW).click()
        edit = self.element_is_visible(table.ADDITINAL_EDIT)
        edit.click()
        edit.send_keys("Подсказка в форме редактирование")
        self.element_is_visible(table.SAVE).click()
    def use_directory(self):#Создание таблицы, использующей справочник
        self.autorization()
        self.element_is_visible(table.ADD_TABLE).click()
        table_name=self.element_is_visible(table.TABLE_NAME)
        table_name.send_keys("Таблица 1 31.03.2023")
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.SECOND_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('Строка')
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DIRECTORY).click()
        self.element_is_visible(table.SETTING_ADDITINAL).click()
        self.element_is_visible(table.NAMES_ADDITINAL).click()
        names_additional=self.element_is_visible(table.INPUT_NAMES_ADDITINAL)
        names_additional.send_keys("Справочник 1 31.03.2023")
        names_additional.send_keys(Keys.ENTER)
        self.element_is_visible(table.UNIQUE_COLUMN).click()
        ID=self.element_is_visible(table.INPUT_UNIQUE_COLUMN)
        ID.send_keys("id")
        ID.send_keys(Keys.ENTER)
        self.element_is_visible(table.COLUMN_VIEW).click()
        view = self.element_is_visible(table.INPUT_COLUMN_VIEW)
        view.send_keys("Строка")
        view.send_keys(Keys.ENTER)
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.THiRD_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('Многострочная строка')
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DIRECTORY).click()
        self.element_is_visible(table.NAMES_ADDITINAL).click()
        names_additional = self.element_is_visible(table.INPUT_NAMES_ADDITINAL)
        names_additional.send_keys("Справочник 1 31.03.2023")
        names_additional.send_keys(Keys.ENTER)
        self.element_is_visible(table.UNIQUE_COLUMN).click()
        ID = self.element_is_visible(table.INPUT_UNIQUE_COLUMN)
        ID.send_keys("id")
        ID.send_keys(Keys.ENTER)
        self.element_is_visible(table.COLUMN_VIEW).click()
        view = self.element_is_visible(table.INPUT_COLUMN_VIEW)
        view.send_keys("Многострочная строка")
        view.send_keys(Keys.ENTER)
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.FOUR_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('Целое число')
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DIRECTORY).click()
        self.element_is_visible(table.NAMES_ADDITINAL).click()
        names_additional = self.element_is_visible(table.INPUT_NAMES_ADDITINAL)
        names_additional.send_keys("Справочник 1 31.03.2023")
        names_additional.send_keys(Keys.ENTER)
        self.element_is_visible(table.UNIQUE_COLUMN).click()
        ID = self.element_is_visible(table.INPUT_UNIQUE_COLUMN)
        ID.send_keys("id")
        ID.send_keys(Keys.ENTER)
        self.element_is_visible(table.COLUMN_VIEW).click()
        view=self.element_is_visible(table.INPUT_COLUMN_VIEW)
        view.send_keys("Целое число")
        view.send_keys(Keys.ENTER)
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.FIFTH_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('Число с плавающей точкой')
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DIRECTORY).click()
        self.element_is_visible(table.NAMES_ADDITINAL).click()
        names_additional = self.element_is_visible(table.INPUT_NAMES_ADDITINAL)
        names_additional.send_keys("Справочник 1 31.03.2023")
        names_additional.send_keys(Keys.ENTER)
        self.element_is_visible(table.UNIQUE_COLUMN).click()
        ID = self.element_is_visible(table.INPUT_UNIQUE_COLUMN)
        ID.send_keys("id")
        ID.send_keys(Keys.ENTER)
        self.element_is_visible(table.COLUMN_VIEW).click()
        view = self.element_is_visible(table.INPUT_COLUMN_VIEW)
        view.send_keys("Число с плавающей точкой")
        view.send_keys(Keys.ENTER)
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.SIXTH_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('Дата')
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DIRECTORY).click()
        self.element_is_visible(table.NAMES_ADDITINAL).click()
        names_additional = self.element_is_visible(table.INPUT_NAMES_ADDITINAL)
        names_additional.send_keys("Справочник 1 31.03.2023")
        names_additional.send_keys(Keys.ENTER)
        self.element_is_visible(table.UNIQUE_COLUMN).click()
        ID = self.element_is_visible(table.INPUT_UNIQUE_COLUMN)
        ID.send_keys("id")
        ID.send_keys(Keys.ENTER)
        self.element_is_visible(table.COLUMN_VIEW).click()
        view = self.element_is_visible(table.INPUT_COLUMN_VIEW)
        view.send_keys("Дата")
        view.send_keys(Keys.ENTER)
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.SEVENTH_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('Дата и время')
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DIRECTORY).click()
        self.element_is_visible(table.NAMES_ADDITINAL).click()
        names_additional = self.element_is_visible(table.INPUT_NAMES_ADDITINAL)
        names_additional.send_keys("Справочник 1 31.03.2023")
        names_additional.send_keys(Keys.ENTER)
        self.element_is_visible(table.UNIQUE_COLUMN).click()
        ID = self.element_is_visible(table.INPUT_UNIQUE_COLUMN)
        ID.send_keys("id")
        ID.send_keys(Keys.ENTER)
        self.element_is_visible(table.COLUMN_VIEW).click()
        view = self.element_is_visible(table.INPUT_COLUMN_VIEW)
        view.send_keys("Дата и время")
        view.send_keys(Keys.ENTER)
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.EIGHTH_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('Логическое значение')
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DIRECTORY).click()
        self.element_is_visible(table.NAMES_ADDITINAL).click()
        names_additional = self.element_is_visible(table.INPUT_NAMES_ADDITINAL)
        names_additional.send_keys("Справочник 1 31.03.2023")
        names_additional.send_keys(Keys.ENTER)
        self.element_is_visible(table.UNIQUE_COLUMN).click()
        ID = self.element_is_visible(table.INPUT_UNIQUE_COLUMN)
        ID.send_keys("id")
        ID.send_keys(Keys.ENTER)
        self.element_is_visible(table.COLUMN_VIEW).click()
        view = self.element_is_visible(table.INPUT_COLUMN_VIEW)
        view.send_keys("Логическое значение")
        view.send_keys(Keys.ENTER)
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.NINETH_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('Файл')
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DIRECTORY).click()
        self.element_is_visible(table.NAMES_ADDITINAL).click()
        names_additional = self.element_is_visible(table.INPUT_NAMES_ADDITINAL)
        names_additional.send_keys("Справочник 1 31.03.2023")
        names_additional.send_keys(Keys.ENTER)
        self.element_is_visible(table.UNIQUE_COLUMN).click()
        ID = self.element_is_visible(table.INPUT_UNIQUE_COLUMN)
        ID.send_keys("id")
        ID.send_keys(Keys.ENTER)
        self.element_is_visible(table.COLUMN_VIEW).click()
        view = self.element_is_visible(table.INPUT_COLUMN_VIEW)
        view.send_keys("Файл")
        view.send_keys(Keys.ENTER)
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.TENTH_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('HTML')
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DIRECTORY).click()
        self.element_is_visible(table.NAMES_ADDITINAL).click()
        names_additional = self.element_is_visible(table.INPUT_NAMES_ADDITINAL)
        names_additional.send_keys("Справочник 1 31.03.2023")
        names_additional.send_keys(Keys.ENTER)
        self.element_is_visible(table.UNIQUE_COLUMN).click()
        ID = self.element_is_visible(table.INPUT_UNIQUE_COLUMN)
        ID.send_keys("id")
        ID.send_keys(Keys.ENTER)
        self.element_is_visible(table.COLUMN_VIEW).click()
        view = self.element_is_visible(table.INPUT_COLUMN_VIEW)
        view.send_keys("HTML")
        view.send_keys(Keys.ENTER)
        self.element_is_visible(table.SAVE).click()

    def multiple_table(self):  # 15.Создание таблицы, использующей справочник с множественным выбором
        self.autorization()
        self.element_is_visible(table.ADD_TABLE).click()
        table_name = self.element_is_visible(table.TABLE_NAME)
        table_name.send_keys("Таблица 3 02.04.2023")
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.SECOND_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('Строка')
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DIRECTORY).click()
        self.element_is_visible(table.SETTING_ADDITINAL).click()
        self.element_is_visible(table.NAMES_ADDITINAL).click()
        names_additional = self.element_is_visible(table.INPUT_NAMES_ADDITINAL)
        names_additional.send_keys("Справочник 1 31.03.2023")
        names_additional.send_keys(Keys.ENTER)
        self.element_is_visible(table.UNIQUE_COLUMN).click()
        ID = self.element_is_visible(table.INPUT_UNIQUE_COLUMN)
        ID.send_keys("id")
        ID.send_keys(Keys.ENTER)
        self.element_is_visible(table.COLUMN_VIEW).click()
        view = self.element_is_visible(table.INPUT_COLUMN_VIEW)
        view.send_keys("Строка")
        view.send_keys(Keys.ENTER)
        self.element_is_visible(table.MANY_CHOICE).click()
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.THiRD_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('Многострочная строка')
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DIRECTORY).click()
        self.element_is_visible(table.NAMES_ADDITINAL).click()
        names_additional = self.element_is_visible(table.INPUT_NAMES_ADDITINAL)
        names_additional.send_keys("Справочник 1 31.03.2023")
        names_additional.send_keys(Keys.ENTER)
        self.element_is_visible(table.UNIQUE_COLUMN).click()
        ID = self.element_is_visible(table.INPUT_UNIQUE_COLUMN)
        ID.send_keys("id")
        ID.send_keys(Keys.ENTER)
        self.element_is_visible(table.COLUMN_VIEW).click()
        view = self.element_is_visible(table.INPUT_COLUMN_VIEW)
        view.send_keys("Многострочная строка")
        view.send_keys(Keys.ENTER)
        self.element_is_visible(table.MANY_CHOICE).click()
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.FOUR_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('Целое число')
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DIRECTORY).click()
        self.element_is_visible(table.NAMES_ADDITINAL).click()
        names_additional = self.element_is_visible(table.INPUT_NAMES_ADDITINAL)
        names_additional.send_keys("Справочник 1 31.03.2023")
        names_additional.send_keys(Keys.ENTER)
        self.element_is_visible(table.UNIQUE_COLUMN).click()
        ID = self.element_is_visible(table.INPUT_UNIQUE_COLUMN)
        ID.send_keys("id")
        ID.send_keys(Keys.ENTER)
        self.element_is_visible(table.COLUMN_VIEW).click()
        view = self.element_is_visible(table.INPUT_COLUMN_VIEW)
        view.send_keys("Целое число")
        view.send_keys(Keys.ENTER)
        self.element_is_visible(table.MANY_CHOICE).click()
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.FIFTH_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('Число с плавающей точкой')
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DIRECTORY).click()
        self.element_is_visible(table.NAMES_ADDITINAL).click()
        names_additional = self.element_is_visible(table.INPUT_NAMES_ADDITINAL)
        names_additional.send_keys("Справочник 1 31.03.2023")
        names_additional.send_keys(Keys.ENTER)
        self.element_is_visible(table.UNIQUE_COLUMN).click()
        ID = self.element_is_visible(table.INPUT_UNIQUE_COLUMN)
        ID.send_keys("id")
        ID.send_keys(Keys.ENTER)
        self.element_is_visible(table.COLUMN_VIEW).click()
        view = self.element_is_visible(table.INPUT_COLUMN_VIEW)
        view.send_keys("Число с плавающей точкой")
        view.send_keys(Keys.ENTER)
        self.element_is_visible(table.MANY_CHOICE).click()
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.SIXTH_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('Дата')
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DIRECTORY).click()
        self.element_is_visible(table.NAMES_ADDITINAL).click()
        names_additional = self.element_is_visible(table.INPUT_NAMES_ADDITINAL)
        names_additional.send_keys("Справочник 1 31.03.2023")
        names_additional.send_keys(Keys.ENTER)
        self.element_is_visible(table.UNIQUE_COLUMN).click()
        ID = self.element_is_visible(table.INPUT_UNIQUE_COLUMN)
        ID.send_keys("id")
        ID.send_keys(Keys.ENTER)
        self.element_is_visible(table.COLUMN_VIEW).click()
        view = self.element_is_visible(table.INPUT_COLUMN_VIEW)
        view.send_keys("Дата")
        view.send_keys(Keys.ENTER)
        self.element_is_visible(table.MANY_CHOICE).click()
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.SEVENTH_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('Дата и время')
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DIRECTORY).click()
        self.element_is_visible(table.NAMES_ADDITINAL).click()
        names_additional = self.element_is_visible(table.INPUT_NAMES_ADDITINAL)
        names_additional.send_keys("Справочник 1 31.03.2023")
        names_additional.send_keys(Keys.ENTER)
        self.element_is_visible(table.UNIQUE_COLUMN).click()
        ID = self.element_is_visible(table.INPUT_UNIQUE_COLUMN)
        ID.send_keys("id")
        ID.send_keys(Keys.ENTER)
        self.element_is_visible(table.COLUMN_VIEW).click()
        view = self.element_is_visible(table.INPUT_COLUMN_VIEW)
        view.send_keys("Дата и время")
        view.send_keys(Keys.ENTER)
        self.element_is_visible(table.MANY_CHOICE).click()
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.EIGHTH_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('Логическое значение')
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DIRECTORY).click()
        self.element_is_visible(table.NAMES_ADDITINAL).click()
        names_additional = self.element_is_visible(table.INPUT_NAMES_ADDITINAL)
        names_additional.send_keys("Справочник 1 31.03.2023")
        names_additional.send_keys(Keys.ENTER)
        self.element_is_visible(table.UNIQUE_COLUMN).click()
        ID = self.element_is_visible(table.INPUT_UNIQUE_COLUMN)
        ID.send_keys("id")
        ID.send_keys(Keys.ENTER)
        self.element_is_visible(table.COLUMN_VIEW).click()
        view = self.element_is_visible(table.INPUT_COLUMN_VIEW)
        view.send_keys("Логическое значение")
        view.send_keys(Keys.ENTER)
        self.element_is_visible(table.MANY_CHOICE).click()
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.NINETH_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('Файл')
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DIRECTORY).click()
        self.element_is_visible(table.NAMES_ADDITINAL).click()
        names_additional = self.element_is_visible(table.INPUT_NAMES_ADDITINAL)
        names_additional.send_keys("Справочник 1 31.03.2023")
        names_additional.send_keys(Keys.ENTER)
        self.element_is_visible(table.UNIQUE_COLUMN).click()
        ID = self.element_is_visible(table.INPUT_UNIQUE_COLUMN)
        ID.send_keys("id")
        ID.send_keys(Keys.ENTER)
        self.element_is_visible(table.COLUMN_VIEW).click()
        view = self.element_is_visible(table.INPUT_COLUMN_VIEW)
        view.send_keys("Файл")
        view.send_keys(Keys.ENTER)
        self.element_is_visible(table.MANY_CHOICE).click()
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.TENTH_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('HTML')
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DIRECTORY).click()
        self.element_is_visible(table.NAMES_ADDITINAL).click()
        names_additional = self.element_is_visible(table.INPUT_NAMES_ADDITINAL)
        names_additional.send_keys("Справочник 1 31.03.2023")
        names_additional.send_keys(Keys.ENTER)
        self.element_is_visible(table.UNIQUE_COLUMN).click()
        ID = self.element_is_visible(table.INPUT_UNIQUE_COLUMN)
        ID.send_keys("id")
        ID.send_keys(Keys.ENTER)
        self.element_is_visible(table.COLUMN_VIEW).click()
        view = self.element_is_visible(table.INPUT_COLUMN_VIEW)
        view.send_keys("HTML")
        view.send_keys(Keys.ENTER)
        self.element_is_visible(table.MANY_CHOICE).click()
        self.element_is_visible(table.SAVE).click()

    def between_tables(self):  # 16.Создание перехода в другую таблицу
        self.autorization()
        self.element_is_visible(table.EDIT_TABLE1).click()
        self.element_is_visible(table.SECOND_ROW).click()
        self.element_is_visible(table.ADD_ADDITINAL_SETTING).click()
        self.element_is_visible(table.TRANSLITION_TABLE).click()
        self.element_is_visible(table.TRANSLITION).click()
        input=self.element_is_visible(table.INPUT_TRANSLITION_TABLE)
        input.click()
        input.send_keys("Справочник 1 31.03.202")
        input.send_keys(Keys.ENTER)
        self.element_is_visible(table.TRANSLITION_FROM).click()
        f=self.element_is_visible(table.INPUT_TRANSLITION_FROM)
        f.click()
        f.send_keys("строка")
        f.send_keys(Keys.ENTER)
        self.element_is_visible(table.TRANSLITION_TO).click()
        to = self.element_is_visible(table.INPUT_TRANSLITION_TO)
        to.click()
        to.send_keys("id")
        to.send_keys(Keys.ENTER)
        self.element_is_visible(table.SAVE).click()
    def add_copy(self): #14.Создание зависимых справочников
        self.autorization()
        self.element_is_visible(table.EDIT_TABLE1).click()

        self.element_is_visible(table.SAVE_AS).click()
        Table_name = self.element_is_visible(table.NAMES_COPY_NAMES)
        Table_name.clear()
        Table_name.send_keys("Таблица 1 копия 05.04.2023")
        #Table_names = self.element_is_visible(table.NAMES_COPY_NAMES)
        #Table_names.clear()
        #Table_names.send_keys("Таблица 1 31.03.2023")
        #self.element_is_visible(table.SAVES).click()

    def add_editForm(self):  # 17.Создание разрешения добавления в форме редактирования для справочника
        self.autorization()
        self.element_is_visible(table.EDIT_TABLE1).click()
        self.element_is_visible(table.THiRD_ROW).click()
        self.element_is_visible(table.SETTING_ADDITINAL).click()
        self.element_is_visible(table.ADD_EDITDORM).click()
        self.element_is_visible(table.SAVE).click()
    def delete_table(self):  # 20.Создание разрешения добавления в форме редактирования для справочника
        self.autorization()
        self.element_is_visible(table.ADD_TABLE).click()
        Table_name = self.element_is_visible(table.TABLE_NAME)
        Table_name.click()
        Table_name.send_keys("Таблица для удаления 03.04.2023")
        self.element_is_visible(table.SAVE).click()
        self.element_is_visible(table.EDITS_TABLE).click()
        self.element_is_visible(table.DELETE_TABLE).click()
        names=self.element_is_visible(table.INPUT_NAME_TABLE_DELETE)
        names.click()
        names.send_keys("Таблица для удаления 03.04.2023")
        time.sleep(2)
        self.element_is_present(table.DELETE_BUTTON_TABLE).click()
        return self.element_is_visible(table.ERRORS_TEXT).text
    def edit_table_name(self): #21.Редактирование Alias и названий таблиц
        self.autorization()
        self.element_is_visible(table.EDIT_ADDITIONAL).click()
        Table_name = self.element_is_visible(table.TABLE_NAME)
        Table_name.click()
        Table_name.clear()
        Table_name.send_keys("Справочник 31.03.2023")
        self.element_is_visible(table.EDITS_TABLE).click()
        alias=self.element_is_visible(table.ALIAS_TABLE_NAME)
        alias.click()
        alias.clear()
        alias.send_keys("Справочник 31.03.2023")
        self.element_is_visible(table.ACCEPT).click()
        self.element_is_visible(table.FIRST_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('Номер')
        self.element_is_visible(table.SETTING_DEVELOP).click()
        alis=self.element_is_visible(table.ALIAS_ROW_NAME)
        alis.click()
        alis.clear()
        alis.send_keys("Номер")
        self.element_is_visible(table.SAVE).click()

    def matches_row(self): #22.Смена местами Alias и названий нескольких столбцов
        self.autorization()
        self.element_is_visible(table.EDIT_ADDITIONAL).click()
        self.element_is_visible(table.SECOND_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('Многострочная строка')
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_MANY_STRING).click()
        self.element_is_visible(table.THiRD_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys('Строка')
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_STRING).click()
        self.element_is_visible(table.SAVE).click()
        return self.element_is_visible(table.ERRORS_TEXT).text

    def moving_rows(self):  # 23.Перемещение столбцов
        self.autorization()
        self.element_is_visible(table.EDIT_ADDITIONAL).click()
        self.element_is_visible(table.SECOND_ROW).click()
        self.element_is_visible(table.STRING_DOWN).click()
        self.element_is_visible(table.SAVE).click()

    def fix_number(self):  #24.Закрепление столбца
        self.autorization()
        self.element_is_visible(table.EDIT_ADDITIONAL).click()
        self.element_is_visible(table.FIRST_ROW).click()
        self.element_is_visible(table.ADD_ADDITINAL_SETTING).click()
        self.element_is_visible(table.fix).click()
        self.element_is_visible(table.SAVE).click()

    def test_status(self):  # 25.Отключение статусов
        self.autorization()
        self.element_is_visible(table.EDIT_ADDITIONAL).click()
        self.element_is_visible(table.STATUS).click()
        self.element_is_visible(table.CHECKBOX_STATUS).click()
        self.element_is_visible(table.SAVE).click()
    def change_dimesnion(self):  # 26.Изменение ширины ячейки в форме редактирования
        self.autorization()
        self.element_is_visible(table.EDIT_ADDITIONAL).click()
        self.element_is_visible(table.THiRD_ROW).click()
        self.element_is_visible(table.ADD_ADDITINAL_SETTING).click()
        self.element_is_visible(table.CHANGE_DIMENSION).click()
        self.element_is_visible(table.DIMENSION12).click()
        self.element_is_visible(table.SAVE).click()

    def change_sample(self):  # 27.Изменение шаблона ячейки
        self.autorization()
        self.element_is_visible(table.EDIT_ADDITIONAL).click()
        self.element_is_visible(table.FIFTH_ROW).click()
        self.element_is_visible(table.SETTING_DEVELOP).click()
        self.element_is_visible(table.SAMPLE_CELL).click()
        cell=self.element_is_visible(table.INPUT_SAMPLE_CELL)
        cell.send_keys("0,00")
        self.element_is_visible(table.SAVE).click()

    def chance_edit_rows(self):  # 28.Возможность редактирования в строке
        self.autorization()
        self.element_is_visible(table.EDIT_ADDITIONAL).click()
        self.element_is_visible(table.EDITS_TABLE).click()
        self.element_is_present(table.EDIT_DATA_WINDOW).click()
        self.element_is_present(table.EDIT_DATA_TABLE).click()
        self.element_is_visible(table.ACCEPT).click()
        self.element_is_visible(table.SAVE).click()

    def add_unique_row(self):  # 30.Создание уникального и обязательного для заполнения поля
        self.autorization()
        self.element_is_visible(table.EDIT_ADDITIONAL).click()
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.ELEVENTH_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys("Проверка")
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_INTENGER).click()
        self.element_is_present(table.CHECK_UNIQUE).click()
        self.element_is_present(table.CHECK_REQUIRED).click()
        self.element_is_visible(table.SAVE).click()

    def off_unique_checkbox(self):  # 31.Создание уникального и обязательного для заполнения поля
        self.autorization()
        self.element_is_visible(table.EDIT_ADDITIONAL).click()
        self.element_is_visible(table.ELEVENTH_ROW).click()
        self.element_is_present(table.CHECK_UNIQUE).click()
        self.element_is_present(table.CHECK_REQUIRED).click()
        self.element_is_visible(table.SAVE).click()











class Table_in_table(BasePage):
        #Создание типа данных таблица внутри таблицы
    def table_order(self):#создание таблицы заказ
        self.autorization()
        self.element_is_present(table.ADD_TABLE).click()
        Table_name = self.element_is_visible(table.TABLE_NAME)
        Table_name.click()
        Table_name.send_keys("Заказ 01.04.2023")
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.SECOND_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys("Дата")
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DATA).click()
        self.element_is_visible(table.SAVE).click()

    def create_position_order(self):#создание позиции в заказе
       # self.autorization()
        self.element_is_visible(table.KONSTRUCTOR).click()
        self.element_is_present(table.ADD_TABLE).click()
        Table_name = self.element_is_visible(table.TABLE_NAME)
        Table_name.click()
        Table_name.send_keys("Позиции в заказе 01.04.2023")
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.SECOND_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys("Название позиции")
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_STRING).click()
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.THiRD_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys("Заказ")
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DIRECTORY).click()
        self.element_is_visible(table.SETTING_ADDITINAL).click()
        self.element_is_visible(table.NAMES_ADDITINAL).click()
        names_additional = self.element_is_visible(table.INPUT_NAMES_ADDITINAL)
        names_additional.send_keys("Заказ 01.04.2023")
        names_additional.send_keys(Keys.ENTER)
        self.element_is_visible(table.UNIQUE_COLUMN).click()
        ID = self.element_is_visible(table.INPUT_UNIQUE_COLUMN)
        ID.send_keys("id")
        ID.send_keys(Keys.ENTER)
        self.element_is_visible(table.COLUMN_VIEW).click()
        view = self.element_is_visible(table.INPUT_COLUMN_VIEW)
        view.send_keys("id")
        view.send_keys(Keys.ENTER)
        self.element_is_visible(table.SAVE).click()

    def create_position(self): #добавление колонку позиции
        self.autorization()
        self.element_is_visible(table.KONSTRUCTOR).click()
        self.element_is_visible(table.EDIT_ORDER).click()
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.THiRD_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys("Позиции")
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_TABLE).click()
        self.element_is_visible(table.SETTING_TABLE).click()
        self.element_is_visible(table.TAKE_DATA).click()
        self.element_is_visible(table.INPUT_TAKE_DATA).click()
        self.element_is_visible(table.POSITION_TAKE_DATA).click()
        self.element_is_visible(table.VIEW_DATA).click()
        self.element_is_visible(table.INPUT_VIEW_DATA).send_keys("Название позиции")
        self.element_is_visible(table.INPUT_VIEW_DATA).send_keys(Keys.ENTER)
        self.element_is_visible(table.SAVE).click()
class Test_dependent_directory(BasePage):
    def create_table_type(self):
         self.autorization()
         self.element_is_visible(table.ADD_TABLE).click()
         Table_name = self.element_is_visible(table.TABLE_NAME)
         Table_name.click()
         Table_name.send_keys("тип данных 01.04.2023")
         self.element_is_visible(table.ADD_ROW).click()
         self.element_is_visible(table.SECOND_ROW).click()
         names = self.element_is_visible(table.NAMES)
         names.click()
         names.clear()
         names.send_keys("название типа")
         self.element_is_visible(table.SAVE).click()

    def create_table_data(self):
        #self.autorization()
        self.element_is_visible(table.KONSTRUCTOR).click()
        self.element_is_visible(table.ADD_TABLE).click()
        Table_name = self.element_is_visible(table.TABLE_NAME)
        Table_name.click()
        Table_name.send_keys("данные 01.04.2023")
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.SECOND_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys("данные")
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.THiRD_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys("название типа")
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DIRECTORY).click()
        self.element_is_visible(table.SETTING_ADDITINAL).click()
        self.element_is_visible(table.NAMES_ADDITINAL).click()
        names_additional = self.element_is_visible(table.INPUT_NAMES_ADDITINAL)
        names_additional.send_keys("тип данных 01.04.2023")
        names_additional.send_keys(Keys.ENTER)
        self.element_is_visible(table.UNIQUE_COLUMN).click()
        ID = self.element_is_visible(table.INPUT_UNIQUE_COLUMN)
        ID.send_keys("id")
        ID.send_keys(Keys.ENTER)
        self.element_is_visible(table.COLUMN_VIEW).click()
        view = self.element_is_visible(table.INPUT_COLUMN_VIEW)
        view.send_keys("название типа")
        view.send_keys(Keys.ENTER)
        self.element_is_visible(table.SAVE).click()
    def create_table_addiction(self):
        self.autorization()
        #self.element_is_visible(table.KONSTRUCTOR).click()
        self.element_is_visible(table.ADD_TABLE).click()
        Table_name = self.element_is_visible(table.TABLE_NAME)
        Table_name.click()
        Table_name.send_keys("зависимость 01.04.2023")
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.SECOND_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys("название типа")
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DIRECTORY).click()
        self.element_is_visible(table.SETTING_ADDITINAL).click()
        self.element_is_visible(table.NAMES_ADDITINAL).click()
        names_additional = self.element_is_visible(table.INPUT_NAMES_ADDITINAL)
        names_additional.send_keys("тип данных 01.04.2023")
        names_additional.send_keys(Keys.ENTER)
        self.element_is_visible(table.UNIQUE_COLUMN).click()
        ID = self.element_is_visible(table.INPUT_UNIQUE_COLUMN)
        ID.send_keys("id")
        ID.send_keys(Keys.ENTER)
        self.element_is_visible(table.COLUMN_VIEW).click()
        view = self.element_is_visible(table.INPUT_COLUMN_VIEW)
        view.send_keys("название типа")
        view.send_keys(Keys.ENTER)
        self.element_is_visible(table.ADD_ROW).click()
        self.element_is_visible(table.THiRD_ROW).click()
        names = self.element_is_visible(table.NAMES)
        names.click()
        names.clear()
        names.send_keys("данные")
        self.element_is_visible(table.TYPE).click()
        self.element_is_visible(table.TYPE_DIRECTORY).click()
        self.element_is_visible(table.NAMES_ADDITINAL).click()
        names_additional = self.element_is_visible(table.INPUT_NAMES_ADDITINAL)
        names_additional.send_keys("данные 01.04.2023")
        names_additional.send_keys(Keys.ENTER)
        self.element_is_visible(table.UNIQUE_COLUMN).click()
        ID = self.element_is_visible(table.INPUT_UNIQUE_COLUMN)
        ID.send_keys("id")
        ID.send_keys(Keys.ENTER)
        self.element_is_visible(table.COLUMN_VIEW).click()
        view = self.element_is_visible(table.INPUT_COLUMN_VIEW)
        view.send_keys("название типа")
        view.send_keys(Keys.ENTER)
        self.element_is_visible(table.SAVE).click()





























